version: 2
jobs:
  macos_npm:
    macos:
      xcode: "9.1.0"
    steps:
      - checkout
      - run: brew upgrade npm
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm build
      - run: npm install --global .
      - run: npm run test
  macos_yarn:
    macos:
      xcode: "9.1.0"
    steps:
      - checkout
      - run: brew upgrade yarn
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: yarn --version
      - run: yarn install
      - run: yarn run build
      - run: yarn global add file:$PWD
      - run: yarn run pretest
      - run: yarn run test:yarn
  linux_npm:
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: sudo npm install --global . --no-optional
      - run: npm run test
  linux_yarn:
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout
      - run: node --version
      - run: yarn --version
      - run: yarn install
      - run: yarn run build
      - run: yarn global add file:$PWD
      - run: yarn run pretest
      - run: yarn run test:yarn

workflows:
  version: 2
  build:
    jobs:
      - macos_npm
      - macos_yarn
      - linux_npm
      - linux_yarn
